export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAIL = 'FETCH_MOVIES_FAIL';

export const FETCH_MOVIE_DETAIL_SUCCESS = 'FETCH_MOVIE_DETAIL_SUCCESS';
export const FETCH_MOVIE_DETAIL_FAIL = 'FETCH_MOVIE_DETAIL_FAIL';

export const FETCH_MOVIE_IMAGE_SUCCESS = 'FETCH_MOVIE_IMAGE_SUCCESS';
export const FETCH_MOVIE_IMAGE_FAIL = 'FETCH_MOVIE_IMAGE_FAIL';
export const FETCH_MOVIE_IMAGE_START = 'FETCH_MOVIE_IMAGE_START';
export const CLEAR_IMAGE = 'CLEAR_IMAGE';